### PR TITLE
Fix timestamp issue

### LINKED ISSUE #8: current_date() in data_freshness_assertions does not work with hours/minutes/seconds
Current_date should be replaced with current_timestamps to avoid the error of when running assertions based on HOURS/MINUTES diffs. 

https://github.com/devoteamgcloud/dataform-assertions/pull/7

This pull request solves it.

### PR DESCRIPTION
**Pull request by hrialan**
fixes #8

### CODE REVIEW

**Comment by hrialan** [comment]
Hello, 

I tried to solve your issue @alexvys, does it meet your needs?

@tanukifk, Can you please also take a look since you worked on the timezone topic? 

Thanks!

**Comment by hrialan** [comment]
Error it fixes:

Capture d’écran 2024-05-22 à 11 38 40

**Comment by alexvys** [comment]
`TIMESTAMP_DIFF(CURRENT_TIMESTAMP("${timeZone}"), MAX(${dateColumn}), ${timeUnit}) AS delay`

I think this could also work

**Comment by tanukifk** [comment]
Thank you for notifying me.
Because timestamp_diff and date_diff take different granularity, we need to use both two functions based on arguments.

I think this conditional variable can fix the problem.
```
comparisonFunction = timeUnit in ('DAY', "WEEK", "MONTH", "QUARTER", "YEAR") 
? `DATE_DIFF(CURRENT_DATE("${timeZone}"), MAX(${dateColumn}), ${timeUnit})` 
: `TIMESTAMP_DIFF(CURRENT_TIMESTAMP(), MAX(${dateColumn}), ${timeUnit})`; 
```

ref
https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#timestamp_diff
https://cloud.google.com/bigquery/docs/reference/standard-sql/date_functions#date_diff

**Pull request merged**
